<?php echo $this->doctype() ?>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=<?=$this->charset?$this->charset:'utf-8';?>" />
    <title>Login Sistema - Entrega</title>	
	<?php
		echo $this->headLink()->appendStylesheet('/css/geral.css');
  		echo $this->headScript()->appendFile('/js/util.js')
								->appendFile('/js/jquery-1.3.2.min.js')
								->appendFile('/js/jquery-watermarkinput.js')
								->appendFile('/js/jquery-corners.js')
								->appendFile('/js/jquery.mask.js')
								->appendFile('/js/jquery-chamadas.js');
	?>
</head>
<body>
	<div id="geral">
		<div align="center">
			<form id="loginForm" method="post">
				<div id="loginLogo">
					<ul class="campos">
						<li class="field">Usuário</li>
						<li><input class="submitenter" type="text" name="usuario"/></li>
					</ul>
					<ul class="campos">
						<li class="field">Senha</li>
						<li><input class="submitenter" type="password" name="senha"/></li>
					</ul>
					<?=$this->erro?'<div class="erro">'.$this->erro.'</div>' : ''?>
					<a class="botao" href="javascript:submit()">Entrar</a>
				</div>
			</form>
		</div>
	</div>
</body>
</html>